In [1]:
import pandas as pd
import requests
pd.set_option('display.max_columns',None)
import time
import numpy as np

In [2]:

# this is the main URL for the page we will be scraping. we will be looping through each page and will be changing key aspects of the URL later.
test_url ='https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2023-24&SeasonType=Regular%20Season&StatCategory=PTS'

In [3]:
r = requests.get(url=test_url).json()
headers = r['resultSet']['headers'] 
pd.DataFrame(r['resultSet']['rowSet'],columns = headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629029,1,Luka Doncic,1610612742,DAL,70,2624,804,1652,0.487,284,744,0.382,478,608,0.786,59,588,647,686,99,38,282,149,2370,2580,2.43,0.35
1,1628983,2,Shai Gilgeous-Alexander,1610612760,OKC,75,2553,796,1487,0.535,95,269,0.353,567,649,0.874,65,350,415,465,150,67,162,184,2254,2416,2.87,0.93
2,203507,3,Giannis Antetokounmpo,1610612749,MIL,73,2567,837,1369,0.611,34,124,0.274,514,782,0.657,196,645,841,476,87,79,250,210,2222,2655,1.90,0.35
3,1628973,4,Jalen Brunson,1610612752,NYK,77,2726,790,1648,0.479,211,526,0.401,421,497,0.847,43,235,278,519,70,13,186,144,2212,1972,2.79,0.38
4,203999,5,Nikola Jokic,1610612743,DEN,79,2737,822,1411,0.583,83,231,0.359,358,438,0.817,223,753,976,708,108,68,237,194,2085,3039,2.99,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,1628382,563,Justin Jackson,1610612750,MIN,2,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
568,1629232,563,Kaiser Gates,1610612740,NOP,1,7,0,4,0.000,0,2,0.000,0,0,0.000,0,1,1,0,0,0,0,0,0,-3,0.00,0.00
569,1630608,563,Malcolm Cazalon,1610612765,DET,1,3,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
570,1631199,563,Ron Harper Jr.,1610612761,TOR,1,4,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,2,0,1,0.00,0.00
571,1627853,563,Ryan Arcidiacono,1610612752,NYK,20,45,0,6,0.000,0,6,0.000,0,0,0.000,0,8,8,4,2,0,2,5,0,6,2.00,1.00

In [4]:
#getting the header for the table set up
df_cols = ['Year','Season_type']+ headers
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [6]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season','Playoffs']
years = ['2013-14','2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']
begin_loop= time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r= requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'],columns = headers)
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                                'Season_type':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2,temp_df1], axis = 1)
        df = pd.concat([df,temp_df3], axis = 0)
        print(f'Finished scraping data for the {y} {s}')
        lag = np.random.uniform(low = 4, high = 30)
        print(f'... waiting {round(lag,1)} seconds.')
        time.sleep(lag)

print(f'process completed. Total runtime: {round((time.time() - begin_loop)/60 ,2)} minutes.')
df.to_excel('Tools/nba_player_data2.xlsx',index = False)

Finished scraping data for the 2013-14 Regular%20Season
... waiting 27.7 seconds.
Finished scraping data for the 2013-14 Playoffs
... waiting 18.1 seconds.
Finished scraping data for the 2014-15 Regular%20Season
... waiting 16.1 seconds.
Finished scraping data for the 2014-15 Playoffs
... waiting 15.9 seconds.
Finished scraping data for the 2015-16 Regular%20Season
... waiting 10.2 seconds.
Finished scraping data for the 2015-16 Playoffs
... waiting 21.9 seconds.
Finished scraping data for the 2016-17 Regular%20Season
... waiting 13.0 seconds.
Finished scraping data for the 2016-17 Playoffs
... waiting 16.8 seconds.
Finished scraping data for the 2017-18 Regular%20Season
... waiting 15.2 seconds.
Finished scraping data for the 2017-18 Playoffs
... waiting 28.9 seconds.
Finished scraping data for the 2018-19 Regular%20Season
... waiting 14.0 seconds.
Finished scraping data for the 2018-19 Playoffs
... waiting 26.0 seconds.
Finished scraping data for the 2019-20 Regular%20Season
... waiting 27.1 seconds.
Finished scraping data for the 2019-20 Playoffs
... waiting 25.1 seconds.
Finished scraping data for the 2020-21 Regular%20Season
... waiting 29.3 seconds.
Finished scraping data for the 2020-21 Playoffs
... waiting 16.8 seconds.
Finished scraping data for the 2021-22 Regular%20Season
... waiting 23.2 seconds.
Finished scraping data for the 2021-22 Playoffs
... waiting 20.5 seconds.
Finished scraping data for the 2022-23 Regular%20Season
... waiting 11.4 seconds.
Finished scraping data for the 2022-23 Playoffs
... waiting 22.0 seconds.
Finished scraping data for the 2023-24 Regular%20Season
... waiting 29.1 seconds.
Finished scraping data for the 2023-24 Playoffs
... waiting 6.2 seconds.
process completed. Total runtime: 0.05 minutes.